openapi: 3.0.3

info:
  title: OpenAPI Specification for Rating Management Service
  version: '1.0'
  
externalDocs:
    description: More Information about Rating Management Service API
    url: https://github.com/nileshmkjee123/RatingmanagementSystem/tree/main
    
servers:
  - url: http://localhost:8080/api/rating
      
tags:
  - name: Requests
    description: Description for requests
        
paths:
  /submit:
    summary: Submit a rating
    post:
      tags:
        - Requests
      summary: Endpoint to submit a rating.
      responses:
        201:
          description: Created
        400:
          description: Bad request
  /update/{id}:
    summary: Update a rating
    put:
      tags:
        - Requests
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Rating'
        required: true
      summary: Endpoint to update a rating.
      responses:
        200:
          description: Updated
        400:
          description: Bad request
  /delete/{id}:
    summary: Delete a rating
    delete:
      tags:
        - Requests
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      summary: Endpoint to delete a rating.
      responses:
        200:
          description: Deleted
  /count:
    summary: count number of ratings.
    get:
      tags:
        - Requests
      summary: Endpoint to count the number of ratings.
      responses:
        200:
          description: count
  /avg:
    summary: find average of all ratings.
    get:
      tags:
        - Requests
      summary: Endpoint to find average of all the ratings.
      responses:
        200:
          description: average
components:
  schemas:
    Rating:
      required:
        - rating
      type: object
      properties:
        id:
          type: string
        rating:
          type: number
          format: double
  
  
  